### ISSUE TITLE
Info Banner pop-up sporadicly if Bravia Sync enabled and HDMI ARC device is connected

### ISSUE THREAD

**Issue by GREMeZ** [CiNcH83/bravia_atv2#100]
Info Banner appears randomly without any oblivious pattern when an AVR or soundbar is connected to ARC port and HDMI CEC is enabled on TV. Resolution, colorspace, framerate, ect. remain unchanged

XF90
Firmware 6.7140
Temporary workaround - turn off the Info Banner for good

**Comment by CiNcH83** [comment]
It does not happen with the following setup:
```
 __________________          ____________
| BRAVIA     HDMI1 |_       |            |
| XF9005     HDMI2 |________| AppleTV 4K |
|        HDMI3/ARC |____    |____________|
|            HDMI4 |_   |    ____________
|__________________|    |___|            |
                            |  Soundbar  |
                            |____________|
```

I think it mainly happens when you connect the playback device through the soundbar/AVR.

**Comment by CiNcH83** [comment]
Can you elaborate on your exact setup?

**Comment by sky4055** [comment]
same issue here :
- Apple TV 4k
- Sony KD65AG8, with Firmware 6.7140

**Comment by CiNcH83** [comment]
@GREMeZ 

Please provide further information on the involved devices and how they are interconnected.
