### ISSUE TITLE
TV not properly switching to HDR mode for VP9.2 content

### ISSUE THREAD

**Issue by CiNcH83** [CiNcH83/bravia_atv2#2]
When VP9.2 HDR content is being played back, the TV does not properly switch to HDR mode. While it detects the content as being HDR, the TV "forgets" to change _Brightness_, _Auto Local Dimming_/_X-tended Dynamic Range_ and color space accordingly, effectively using the SDR settings, also staying in the wrong BT.709 color space.

The issue can be verified by playing [The World in HDR](https://www.youtube.com/watch?v=tO01J-M3g0U) through the YouTube app or by casting it from the YouTube mobile app on Android or iOS to the BRAVIA.

**Comment by Morac2** [comment]
Since Google Movies and TV also uses VP9.2, this bug also affects HDR playback via the Google Movies and TV app.  This is the primary reason I never use that app on my 930e.
