### ISSUE TITLE
Kernel crash when powering on TV while being connected through VPN

### ISSUE THREAD

**Issue by CiNcH83** [CiNcH83/bravia_atv2#27]
VpnService is the official Android API for connecting to a VPN server. It is used by all VPN client apps on Android (like _OpenVPN for Android_).

When putting the TV in standby and turning it back on while being connected through Android VpnService, a severe system crash happens. An app is never supposed to crash the system, only itself. This might be a severe security threat.

The crash (SIGSEGV) seems to happen deep down in the system:
```
--------- beginning of crash
06-19 13:41:16.590 10217 10217 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
06-19 13:41:16.591 10217 10217 F DEBUG   : Build fingerprint: 'Sony/BRAVIA_ATV2_EU/BRAVIA_ATV2:7.0/NRD91N.S36/1.6.0.26.02.1.00:user/release-keys'
06-19 13:41:16.591 10217 10217 F DEBUG   : Revision: '0'
06-19 13:41:16.591 10217 10217 F DEBUG   : ABI: 'arm'
06-19 13:41:16.591 10217 10217 F DEBUG   : pid: 1708, tid: 1887, name: navigator  >>> /basic/dtv_svc <<<
06-19 13:41:16.591 10217 10217 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
06-19 13:41:16.591 10217 10217 F DEBUG   :     r0 00000000  r1 00000000  r2 ffffffff  r3 00000011
06-19 13:41:16.591 10217 10217 F DEBUG   :     r4 67a3efe8  r5 00000000  r6 a8e8ce0c  r7 00000002
06-19 13:41:16.592 10217 10217 F DEBUG   :     r8 6f5f8948  r9 6f5f88d8  sl ffffffff  fp 6f5f88ac
06-19 13:41:16.592 10217 10217 F DEBUG   :     ip 00000000  sp 6f5f8828  lr a78f83ac  pc aad50434  cpsr 200f0010
06-19 13:41:16.989 10217 10217 F DEBUG   : 
06-19 13:41:16.989 10217 10217 F DEBUG   : backtrace:
06-19 13:41:16.990 10217 10217 F DEBUG   :     #00 pc 000bc434  /linux_rootfs/basic/libdtv_common.so (_net_get_dev_ip+176)
06-19 13:41:16.990 10217 10217 F DEBUG   :     #01 pc 000c334c  /linux_rootfs/basic/libdtv_common.so
06-19 13:41:16.990 10217 10217 F DEBUG   :     #02 pc 000caa64  /linux_rootfs/basic/libdtv_common.so (x_dhcpc_get_info+68)
06-19 13:41:16.990 10217 10217 F DEBUG   :     #03 pc 00e50cc4  /linux_rootfs/basic/libmtkapp.so (a_nw_get_crnt_real_ip_info+420)
06-19 13:41:16.990 10217 10217 F DEBUG   :     #04 pc 00949f80  /linux_rootfs/basic/libmtkapp.so
06-19 13:41:16.990 10217 10217 F DEBUG   :     #05 pc 00edffc4  /linux_rootfs/basic/libmtkapp.so (nav_brdcst_msg_to_components+296)
06-19 13:41:16.990 10217 10217 F DEBUG   :     #06 pc 00ee8708  /linux_rootfs/basic/libmtkapp.so
06-19 13:41:16.990 10217 10217 F DEBUG   :     #07 pc 000309f4  /linux_rootfs/basic/libdtv_common.so
06-19 13:41:16.990 10217 10217 F DEBUG   :     #08 pc 0002f91c  /linux_rootfs/basic/libdtv_common.so
06-19 13:41:16.990 10217 10217 F DEBUG   :     #09 pc 00017668  /linux_rootfs/basic/libdtv_osai.so (thread_main+76)
06-19 13:41:16.990 10217 10217 F DEBUG   :     #10 pc 0000be30  /linux_rootfs/basic/libdtv_osai.so (os_drv_thread_main+96)
06-19 13:41:16.990 10217 10217 F DEBUG   :     #11 pc 00006e80  /linux_rootfs/lib/libpthread-2.18.so
06-19 13:41:16.990 10217 10217 F DEBUG   :     #12 pc 000ccd7c  /linux_rootfs/lib/libc-2.18.so
```

VPN needs to be disconnected before putting the TV in standby in order to prevent the crash on resume.

The crash can be reproduced by connecting to some VPN server from the TV. Server and client software do not matter as every VPN connection goes through VpnService on Android. The easiest way to do so is by running an own OpenVPN server on a QNAP or Synology NAS and then connecting to it from the TV via _OpenVPN for Android_ app. TV then has to be put in standby and turned back on ⇒ crash.

**Comment by kingo132** [comment]
my sony z9d also enter this problem, every time I power off the tv and power on again, the tv hang and restart. Surely it is because I installed shadowsocks app, after I turn off the VPN before power off the TV. The problem seems temporarily solved. Thanks for the tip!

**Comment by Morteza-Rastgoo** [comment]
Same issue exists yet on my Sony android tv kd-49x8000g
Any idea how to get this fixed?

[Issue on Sony community](https://community.sony.ru/t5/android-tv/49x8000-restarts-when-wifi-connect-disconnect/m-p/2743600#M43187)

**Comment by Morteza-Rastgoo** [comment]
@CiNcH83  Is this fixed? How long does it takes to release?

**Comment by CiNcH83** [comment]
I could not reproduce it anymore with FW 6.6575. Check your local Sony support page whether the update is already available to be flashed via USB.

**Comment by Morteza-Rastgoo** [comment]
Thanks 👍😊

**Comment by kiddowang4co** [comment]
This happen on my bravia ,thx homie
