### ISSUE TITLE
No DTS passthrough via standard Android AudioTrack API

### ISSUE THREAD

**Issue by CiNcH83** [CiNcH83/bravia_atv2#3]
[ENCODING_DTS](https://developer.android.com/reference/android/media/AudioFormat.html#ENCODING_DTS) and [ENCODING_DTS_HD](https://developer.android.com/reference/android/media/AudioFormat.html#ENCODING_DTS_HD) are implemented according to `AudioDeviceInfo::getEncodings`:
```
--- Found device: BRAVIA 4K GB ATV3
id: 12, type: HDMI_ARC, isSink: true, isSource: false
channel counts: 1 / 2 / 6 / 8
channel index masks: any
channel masks: 4 / 12 / 252 / 6396
encodings: PCM_16BIT / AAC_LC / AAC_HE_V1 / AAC_HE_2 / AC3 / E_AC3 / DTS / DTS_HD
sample rates: 8000 / 11025 / 16000 / 22050 / 24000 / 32000 / 44100 / 48000
```

Unfortunately there is only silence when using the DTS APIs. No stream is output to the AVR. Also the stock _Video_ app is affected.

**Comment by jaketame** [comment]
Is there any status on this being rectified by Sony? Especially when they publish DTS on there soundbars?

**Comment by Rydako** [comment]
Did this get fixed on 6.5850?

**Comment by CiNcH83** [comment]
According to some people on reddit, DTS is indeed fixed. The new firmware even supports [Android's DTS-HD API](https://developer.android.com/reference/android/media/AudioFormat.html#ENCODING_DTS). DTS-HD MA over ARC works as such that the DTS compatible core is extracted for transmission. Playback allegedly stops after two seconds though. Will test as soon as the firmware is available in my region.

**Comment by CiNcH83** [comment]
FW 6.6510 in Europe fixes DTS passthrough.
