### ISSUE TITLE
Screen Mirroring: WiFi Direct connection from Windows 10 fails

### ISSUE THREAD

**Issue by CiNcH83** [CiNcH83/bravia_atv2#87]
Windows 10 fails to connect to the BRAVIA via WiFi Direct when trying to initiate a Screen Mirroring session. This has been tested with a Lenovo Yoga Slim 7, featuring Intel’s AX200 WiFi module.

![image](https://user-images.githubusercontent.com/24539361/99901728-29652b00-2cb9-11eb-8207-512ad584079d.png)

**Comment by GREMeZ** [comment]
Also fails with mobile device such as Samsung Galaxy S7. Could be Pie related.
